version: "3.6"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

#services:
#  api:
#    container_name: my-api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#    - 8080:8080/tcp
#    links:
#      - postgres
#  postgres:
#    container_name: my-db
#    restart: always
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=varadb
#    image: library/postgres:latest
#    ports:
#      - 5432:5432/tcp
#  flyway:
#    container_name: my-flyway
#    environment:
#      - FLYWAY_USER=root
#      - FLYWAY_PASWORD=root
#      - FLYWAY_URL=jdbc:postgresql://postgres:5432/varadb
#      - FLYWAY_SCHEMAS=flyway, postgres
#      - FLYWAY_GROUP=true
#    image: flyway/flyway:latest
#    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
#    volumes:
#    - ./sql_version:/flyway/sql
#    depends_on:
#      - postgres


#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#  db:
#    image: postgres:11
#    container_name: db
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=testdb
#  flyway:



#version: '2'

#
#services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: 'postgres:13.1-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_USER=compose-postgres
#      - POSTGRES_PASSWORD=compose-postgres
#
#


#version: "2.2"
#services:
#  postgres:
#    build: .
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - 5432:5432
#    volumes:
#
#      - postgres-data:/var/lib/postgresql/data
#version: "3"
#services:
#  springapp:
#    build: .
#    container_name: springapp
#    environment:
#
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
#    ports:
#      - 8080:8080
#    restart: always
#    depends_on:
#      - db
#  db:
#    image: postgres
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=testdb
#
#    ports:
#      - 5432:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: always

#  db:
#    container_name: sample_db
#    image: postgres:9.5
#    volumes:
#      - sample_db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=sample
#      - POSTGRES_USER=sample
#      - POSTGRES_DB=sample
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - 5432:5432

#volumes:
#  sample_db: {}

